version: '3.8'
services:
  mongodb:
    image: 'mongo'
    ports:
    - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - data:/data/db/
    container_name: mongodb
  portfolio:
    build: ./
    environment:
      - DBURL=mongodb://user:admin@mongodb:27017/course-goals?authSource=admin
    ports:
      - '80:80'
    volumes:
      - /app/node_modules
      - .:/app/
    container_name: portfolio
    depends_on:
      - mongodb

volumes:
  data:
